# Connections:
#   eth1 -> router2 (cost 20)
#   eth2 -> LAN2 (10.4.0.0/24) - passive, connects to K8s Cluster 2
#
frr version 10.5
!
frr defaults traditional
!
hostname router6
!
no ipv6 forwarding
!
log syslog informational
!
# eth1 is toward router2 
interface eth1
  ip address 10.0.26.6/24
  ip ospf cost 20
!

interface eth2
  ip address 10.4.0.1/24
  ip ospf passive
!

interface lo
  ip address 10.255.0.6/32
  ip ospf passive
!
router ospf
 ospf router-id 10.255.0.6
 network 10.0.26.0/24 area 0.0.0.0
 network 10.4.0.0/24 area 0.0.0.0
!
