# Connections:
#   eth1 -> router3 (cost 15)
#   eth2 -> router2 (cost 10)
#
frr version 10.5
!
frr defaults traditional
!
hostname router5
!
no ipv6 forwarding
!
log syslog informational
!
# eth1 is toward router3 
interface eth1
  ip address 10.0.35.5/24
  ip ospf cost 15
!
# eth2 is toward router2 
interface eth2
  ip address 10.0.52.5/24
  ip ospf cost 10
!

interface lo
  ip address 10.255.0.5/32
  ip ospf passive
!
router ospf
 ospf router-id 10.255.0.5
 network 10.0.35.0/24 area 0.0.0.0
 network 10.0.52.0/24 area 0.0.0.0
!
