# CS 4383/5383 Computer Networks
# Scaffolding example
# 03/04/2026
# 
# Configuration file for router 1
#
# See https://docs.frrouting.org/en/latest/ospfd.html
# for details
#
# OSPF uses link state routing (Dijkstra's)
# Link state are broadcast in Link State Advertisement (LSA)
#
# All collected LSAs are stored in a LSDB (link state database)
#
# Also, note that although # and ! start a comment, if they appear
# somewhere in the middle after a statement, it is taken as part
# of that command. I learned this the hard way :-(. So, now I am
# using comment. I also use ! as line separator
!
# use latest stable version
frr version 10.5
!
# use traditional defaults 
frr defaults traditional
!
# provide the router name
hostname router3
!
# disable IPv6
no ipv6 forwarding
!
# specify the level of logging we desire
log syslog informational
!
# in our topology, our eth1 is in the direction of router 1
interface eth1
  # assign an IP address
  ip address 10.0.20.2/24
  # say the route on this path is high cost
  ip ospf cost 60
!
# in our topology, our eth2 is in the direction of router 2
interface eth2
  # assign an IP address
  ip address 10.0.15.2/24
  # lesser cost to go to router 3
  ip ospf cost 15
!
# in our topology, eth3 is toward our LAN comprising pc3
interface eth3
  # assign an IP address
  ip address 172.16.3.1/24
  # passive interface is one where no neighbor OSPF router
  # exists, and so link state advertisements need not be made
  # on that interface. In our case, the "eth3" is connected to
  # the LAN and so we make it passive
  ip ospf passive
!
# override our loopback IP addr and use it as unique router id
interface lo     
  ip address 10.255.0.3/32
  # We make the lo interface also passive
  ip ospf passive
!
# following is the configuration for OSPF
router ospf
 # use a unique ID (can be an IP addr, here we use the lo addr)
 ospf router-id 10.255.0.3
 # The following are OSPF enabled interfaces
 network 10.0.15.0/24 area 0.0.0.0
 network 10.0.20.0/24 area 0.0.0.0
 network 172.16.3.0/24 area 0.0.0.0
!
# Used for virtual terminal interface (going to be deprecated)
line vty
!
