# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GroceryRobot

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AisleItems(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AisleItems()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAisleItems(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AisleItems
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AisleItems
    def Aisle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AisleItems
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from GroceryRobot.Item import Item
            obj = Item()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AisleItems
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AisleItems
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def AisleItemsStart(builder):
    builder.StartObject(2)

def Start(builder):
    AisleItemsStart(builder)

def AisleItemsAddAisle(builder, aisle):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(aisle), 0)

def AddAisle(builder, aisle):
    AisleItemsAddAisle(builder, aisle)

def AisleItemsAddItems(builder, items):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def AddItems(builder, items):
    AisleItemsAddItems(builder, items)

def AisleItemsStartItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartItemsVector(builder, numElems):
    return AisleItemsStartItemsVector(builder, numElems)

def AisleItemsEnd(builder):
    return builder.EndObject()

def End(builder):
    return AisleItemsEnd(builder)
