# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GroceryRobot

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Item(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Item()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsItem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Item
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Item
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Item
    def Quantity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ItemStart(builder):
    builder.StartObject(2)

def Start(builder):
    ItemStart(builder)

def ItemAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ItemAddName(builder, name)

def ItemAddQuantity(builder, quantity):
    builder.PrependInt32Slot(1, quantity, 0)

def AddQuantity(builder, quantity):
    ItemAddQuantity(builder, quantity)

def ItemEnd(builder):
    return builder.EndObject()

def End(builder):
    return ItemEnd(builder)
