# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GroceryRobot

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RobotMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RobotMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRobotMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RobotMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RobotMessage
    def OrderId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RobotMessage
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RobotMessage
    def ActionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # RobotMessage
    def AisleItems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from GroceryRobot.AisleItems import AisleItems
            obj = AisleItems()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RobotMessage
    def AisleItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RobotMessage
    def AisleItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def RobotMessageStart(builder):
    builder.StartObject(4)

def Start(builder):
    RobotMessageStart(builder)

def RobotMessageAddOrderId(builder, orderId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(orderId), 0)

def AddOrderId(builder, orderId):
    RobotMessageAddOrderId(builder, orderId)

def RobotMessageAddRequestId(builder, requestId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)

def AddRequestId(builder, requestId):
    RobotMessageAddRequestId(builder, requestId)

def RobotMessageAddActionType(builder, actionType):
    builder.PrependInt8Slot(2, actionType, 0)

def AddActionType(builder, actionType):
    RobotMessageAddActionType(builder, actionType)

def RobotMessageAddAisleItems(builder, aisleItems):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(aisleItems), 0)

def AddAisleItems(builder, aisleItems):
    RobotMessageAddAisleItems(builder, aisleItems)

def RobotMessageStartAisleItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAisleItemsVector(builder, numElems):
    return RobotMessageStartAisleItemsVector(builder, numElems)

def RobotMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return RobotMessageEnd(builder)
