# Connections:
#   eth1 -> router1 (cost 20)
#   eth2 -> router2 (cost 15, cross link)
#
frr version 10.5
!
frr defaults traditional
!
hostname router5
!
no ipv6 forwarding
!
log syslog informational
!
interface eth1
  ip address 10.1.15.5/24
  ip ospf cost 20
!
interface eth2
  ip address 10.1.52.5/24
  ip ospf cost 15
!
interface lo
  ip address 10.254.0.5/32
  ip ospf passive
!
router ospf
 ospf router-id 10.254.0.5
 network 10.1.15.0/24 area 0.0.0.0
 network 10.1.52.0/24 area 0.0.0.0
!
