# Connections:
#   eth1 -> router1 (cost 10)
#   eth2 -> LAN1 (10.2.0.0/24) - passive, connects to K8s Cluster 1
#
frr version 10.5
!
frr defaults traditional
!
hostname router4
!
no ipv6 forwarding
!
log syslog informational
!
# eth1 is toward router1 
interface eth1
  ip address 10.0.41.1/24
  ip ospf cost 10
!


interface eth2
  ip address 10.2.0.1/24
  ip ospf passive
!

interface lo
  ip address 10.255.0.4/32
  ip ospf passive
!
router ospf
 ospf router-id 10.255.0.4
 network 10.0.41.0/24 area 0.0.0.0
 network 10.2.0.0/24 area 0.0.0.0
!
