# Connections:
#   eth1 -> router4 (cost 10)
#   eth2 -> router2 (cost 100)
#   eth3 -> router3 (cost 25)
#
frr version 10.5
!
frr defaults traditional
!
hostname router1
!
no ipv6 forwarding
!
log syslog informational
!
# eth1 is toward router4
interface eth1
  ip address 10.0.41.4/24
  ip ospf cost 10
!
# eth2 is toward router2 (backbone) 
interface eth2
  ip address 10.0.12.1/24
  ip ospf cost 100
!
# eth3 is toward router3 
interface eth3
  ip address 10.0.13.1/24
  ip ospf cost 25
!

interface lo
  ip address 10.255.0.1/32
  ip ospf passive
!
router ospf
 ospf router-id 10.255.0.1
 network 10.0.41.0/24 area 0.0.0.0
 network 10.0.12.0/24 area 0.0.0.0
 network 10.0.13.0/24 area 0.0.0.0
!
