# Connections:
#   eth1 -> router1 (cost 100)
#   eth2 -> router5 (cost 10)
#   eth3 -> router6 (cost 20)
#
frr version 10.5
!
frr defaults traditional
!
hostname router2
!
no ipv6 forwarding
!
log syslog informational
!
# eth1 is toward router1 
interface eth1
  ip address 10.0.12.2/24
  ip ospf cost 100
!
# eth2 is toward router5 
interface eth2
  ip address 10.0.52.2/24
  ip ospf cost 10
!
# eth3 is toward router6 
interface eth3
  ip address 10.0.26.2/24
  ip ospf cost 20
!

interface lo
  ip address 10.255.0.2/32
  ip ospf passive
!
router ospf
 ospf router-id 10.255.0.2
 network 10.0.12.0/24 area 0.0.0.0
 network 10.0.52.0/24 area 0.0.0.0
 network 10.0.26.0/24 area 0.0.0.0
!
