# Connections:
#   eth1 -> router1 (cost 25)
#   eth2 -> router5 (cost 15)
#
frr version 10.5
!
frr defaults traditional
!
hostname router3
!
no ipv6 forwarding
!
log syslog informational
!
# eth1 is toward router1 
interface eth1
  ip address 10.0.13.3/24
  ip ospf cost 25
!
# eth2 is toward router5 
interface eth2
  ip address 10.0.35.3/24
  ip ospf cost 15
!

interface lo
  ip address 10.255.0.3/32
  ip ospf passive
!
router ospf
 ospf router-id 10.255.0.3
 network 10.0.13.0/24 area 0.0.0.0
 network 10.0.35.0/24 area 0.0.0.0
!
