# Connections:
#   eth1 -> router4 (cost 10)
#   eth2 -> router2 (cost 80, expensive direct)
#   eth3 -> router5 (cost 20)
#   eth4 -> router3 (cost 30)
#
frr version 10.5
!
frr defaults traditional
!
hostname router1
!
no ipv6 forwarding
!
log syslog informational
!
interface eth1
  ip address 10.1.41.1/24
  ip ospf cost 10
!
interface eth2
  ip address 10.1.12.1/24
  ip ospf cost 80
!
interface eth3
  ip address 10.1.15.1/24
  ip ospf cost 20
!
interface eth4
  ip address 10.1.13.1/24
  ip ospf cost 30
!
interface lo
  ip address 10.254.0.1/32
  ip ospf passive
!
router ospf
 ospf router-id 10.254.0.1
 network 10.1.41.0/24 area 0.0.0.0
 network 10.1.12.0/24 area 0.0.0.0
 network 10.1.15.0/24 area 0.0.0.0
 network 10.1.13.0/24 area 0.0.0.0
!
